# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildShortEvacTime
                                 A QGIS plugin
 Building level Shortest Evacuation Time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-27
        copyright            : (C) 2025 by Gaurav Khairnar
        email                : gaurav.b.khairnar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os 
import pkg_resources
import site
import sys

def add_dependencies():
    extra_libs_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "required_python_packages")
    )
    if os.path.isdir(extra_libs_path) and extra_libs_path not in sys.path:
        sys.path.insert(0, extra_libs_path)
        site.addsitedir(extra_libs_path)
 
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildShortEvacTime class from file BuildShortEvacTime.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    #add_dependencies()
    from .Build_Short_Evac_Time import BuildShortEvacTime
    return BuildShortEvacTime(iface)
